//
// Generated file, do not edit! Created by nedtool 5.6 from frame.msg.
//

#ifndef __FRAME_M_H
#define __FRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>frame.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Frame
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     uint8_t type; //0 for data , 1 for ack , 2 for activate , 3 for end Session
 *     long frameNum; //Frame Number
 *     long sessionNumber;
 *     string payLoad;
 * 
 * }
 * </pre>
 *
 * Frame_Base is only useful if it gets subclassed, and Frame is derived from it.
 * The minimum code to be written for Frame is the following:
 *
 * <pre>
 * class Frame : public Frame_Base
 * {
 *   private:
 *     void copy(const Frame& other) { ... }

 *   public:
 *     Frame(const char *name=nullptr, short kind=0) : Frame_Base(name,kind) {}
 *     Frame(const Frame& other) : Frame_Base(other) {copy(other);}
 *     Frame& operator=(const Frame& other) {if (this==&other) return *this; Frame_Base::operator=(other); copy(other); return *this;}
 *     virtual Frame *dup() const override {return new Frame(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from Frame_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(Frame)
 * </pre>
 */
class Frame_Base : public ::omnetpp::cPacket
{
  protected:
    uint8_t type;
    long frameNum;
    long sessionNumber;
    ::omnetpp::opp_string payLoad;

  private:
    void copy(const Frame_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Frame_Base&);
    // make constructors protected to avoid instantiation

    Frame_Base(const Frame_Base& other);
    // make assignment operator protected to force the user override it
    Frame_Base& operator=(const Frame_Base& other);

  public:
    virtual ~Frame_Base();
    Frame_Base(const char *name=nullptr, short kind=0);
    virtual Frame_Base *dup() const override {return new Frame_Base(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint8_t getType() const;
    virtual void setType(uint8_t type);
    virtual long getFrameNum() const;
    virtual void setFrameNum(long frameNum);
    virtual long getSessionNumber() const;
    virtual void setSessionNumber(long sessionNumber);
    virtual const char * getPayLoad() const;
    virtual void setPayLoad(const char * payLoad);
};


#endif // ifndef __FRAME_M_H


